name: CI Pipeline
on:
  push:
    branches: [master, task-1, task-2]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pytest pandas numpy yfinance
      - name: Download data
        run: python src/data_loader.py
      - name: Run tests
        run: pytest tests/ -v
